name: Build Slate docs

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [3.5.7]

    steps:
    - uses: actions/checkout@v2
    - name: Move into slate-docs directory
      run: cd slate-docs
      working-directory: ${{ github.workspace }}
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: gems-${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}

    # necessary to get ruby 2.3 to work nicely with bundler vendor/bundle cache
    # can remove once ruby 2.3 is no longer supported
    - run: gem update --system

    - run: bundle config set deployment 'true'
    - run: bundle install

    - run: bundle exec middleman build
