name: Build Slate docs

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.7.0]

    steps:
    - uses: actions/checkout@v2
    - name: Move into slate-docs directory
      run: |
        cd slate-docs
        ls -l
      working-directory: ${{ github.workspace }}
    - name: test
      run: |
        cd slate-docs
        ls -l
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: gems-${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}

    - run: bundle config set deployment 'true'
    - run: bundle install

    - run: bundle exec middleman build 
